name: AiCompany
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.4=hd7fb8db_0
  - libexpat=2.7.4=hd7fb8db_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.19=hbb43b14_0
  - pip=26.0.1=pyhc872135_0
  - python=3.9.25=h716150d_1
  - setuptools=80.9.0=py39haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025c=he532380_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py39haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - altgraph==0.17.5
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.1
      - audioread==3.1.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.1.8
      - colorama==0.4.6
      - comtypes==1.4.15
      - decorator==5.2.1
      - distro==1.9.0
      - exceptiongroup==1.3.1
      - fastapi==0.128.8
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - importlib-metadata==8.7.1
      - jiter==0.13.0
      - joblib==1.5.3
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.43.0
      - msgpack==1.1.2
      - numba==0.60.0
      - numpy==2.0.2
      - openai==2.21.0
      - packaging==26.0
      - pefile==2024.8.26
      - pillow==11.3.0
      - platformdirs==4.4.0
      - pooch==1.9.0
      - pyaudio==0.2.14
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.11.0
      - pyinstaller==6.19.0
      - pyinstaller-hooks-contrib==2026.1
      - pypiwin32==223
      - python-dotenv==1.2.1
      - pyttsx3==2.99
      - pywin32==311
      - pywin32-ctypes==0.2.3
      - requests==2.32.5
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soxr==1.0.0
      - speechrecognition==3.14.5
      - starlette==0.49.3
      - threadpoolctl==3.6.0
      - tqdm==4.67.3
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.6.3
      - uvicorn==0.39.0
      - webrtcvad==2.0.10
      - zipp==3.23.0
prefix: D:\Anaconda\envs\AiCompany
